const inscriptionacadColumns = [
            { header: 'Dateinscacad', field: 'dateinscacad', dataKey: 'dateinscacad' },
            { header: 'Passage', field: 'passage', dataKey: 'passage' },
            { header: 'Etat', field: 'etat', dataKey: 'etat' },
            { header: 'Montantinscriptionacad', field: 'montantinscriptionacad', dataKey: 'montantinscriptionacad' },
            { header: 'Coutformation', field: 'coutformation', dataKey: 'coutformation' },
            { header: 'Numquittance', field: 'numquittance', dataKey: 'numquittance' },
            { header: 'Cartetiree', field: 'cartetiree', dataKey: 'cartetiree' },
            { header: 'Certificattire', field: 'certificattire', dataKey: 'certificattire' },
            { header: 'Valide', field: 'valide', dataKey: 'valide' },
            { header: 'QuitusBu', field: 'quitusBu', dataKey: 'quitusBu' },
            { header: 'QuitusSocial', field: 'quitusSocial', dataKey: 'quitusSocial' },
            { header: 'QuitusMedical', field: 'quitusMedical', dataKey: 'quitusMedical' },
            { header: 'QuitusComptabilite', field: 'quitusComptabilite', dataKey: 'quitusComptabilite' },
            { header: 'QuitusVieUniversitaire', field: 'quitusVieUniversitaire', dataKey: 'quitusVieUniversitaire' },
            { header: 'Universitepartenaire', field: 'universitepartenaire', dataKey: 'universitepartenaire' },
            { header: 'Sourcefinancement', field: 'sourcefinancement', dataKey: 'sourcefinancement' },
            { header: 'Coencadreur', field: 'coencadreur', dataKey: 'coencadreur' },
            { header: 'Premiereanneeinscription', field: 'premiereanneeinscription', dataKey: 'premiereanneeinscription' },
            { header: 'Datemodification', field: 'datemodification', dataKey: 'datemodification' },
            { header: 'MoyenneAnnuelle', field: 'moyenneAnnuelle', dataKey: 'moyenneAnnuelle' },
            { header: 'TotalCredit', field: 'totalCredit', dataKey: 'totalCredit' },
            { header: 'CreditCapitalise', field: 'creditCapitalise', dataKey: 'creditCapitalise' },
            { header: 'DecisionConseil', field: 'decisionConseil', dataKey: 'decisionConseil' },
        ];

const allowedInscriptionacadFieldsForFilter = [
    'dateinscacad',
    'passage',
    'etat',
    'montantinscriptionacad',
    'coutformation',
    'numquittance',
    'cartetiree',
    'certificattire',
    'valide',
    'quitusBu',
    'quitusSocial',
    'quitusMedical',
    'quitusComptabilite',
    'quitusVieUniversitaire',
    'universitepartenaire',
    'sourcefinancement',
    'coencadreur',
    'premiereanneeinscription',
    'datemodification',
    'moyenneAnnuelle',
    'totalCredit',
    'creditCapitalise',
    'decisionConseil',
];

export { inscriptionacadColumns,allowedInscriptionacadFieldsForFilter };
