export class Inscriptionacad {
    id: any;
    dateinscacad: string;
    passage: string;
    etat: string;
    montantinscriptionacad: string;
    coutformation: string;
    numquittance: string;
    cartetiree: boolean;
    certificattire: boolean;
    valide: boolean;
    quitusBu: boolean;
    quitusSocial: boolean;
    quitusMedical: boolean;
    quitusComptabilite: boolean;
    quitusVieUniversitaire: boolean;
    universitepartenaire: string;
    sourcefinancement: string;
    coencadreur: string;
    premiereanneeinscription: string;
    datemodification: string;
    moyenneAnnuelle: string;
    totalCredit: string;
    creditCapitalise: string;
    decisionConseil: string;
    idregimeinscription: any;
    idspecialite: any;
    idclasse: any;
    //temporal fields
    preinscirptionId: any;
}
