const etudiantColumns = [
            { header: 'Cni', field: 'cni', dataKey: 'cni' },
            { header: 'Ine', field: 'ine', dataKey: 'ine' },
            { header: 'Numinterne', field: 'numinterne', dataKey: 'numinterne' },
            { header: 'Nometudiant', field: 'nometudiant', dataKey: 'nometudiant' },
            { header: 'Prenometudiant', field: 'prenometudiant', dataKey: 'prenometudiant' },
            { header: 'Genre', field: 'genre', dataKey: 'genre' },
            { header: 'Datenaiss', field: 'datenaiss', dataKey: 'datenaiss' },
            { header: 'Lieunaiss', field: 'lieunaiss', dataKey: 'lieunaiss' },
            { header: 'Regionnaiss', field: 'regionnaiss', dataKey: 'regionnaiss' },
            { header: 'Adville', field: 'adville', dataKey: 'adville' },
            { header: 'Adquartier', field: 'adquartier', dataKey: 'adquartier' },
            { header: 'Adruevilla', field: 'adruevilla', dataKey: 'adruevilla' },
            { header: 'Email', field: 'email', dataKey: 'email' },
            { header: 'EmailUniv', field: 'emailUniv', dataKey: 'emailUniv' },
            { header: 'Notifmail', field: 'notifmail', dataKey: 'notifmail' },
            { header: 'Photo', field: 'photo', dataKey: 'photo' },
            { header: 'Lyceedeprovenance', field: 'lyceedeprovenance', dataKey: 'lyceedeprovenance' },
            { header: 'Teletudiant', field: 'teletudiant', dataKey: 'teletudiant' },
            { header: 'Teletudiant2', field: 'teletudiant2', dataKey: 'teletudiant2' },
            { header: 'Seriebac', field: 'seriebac', dataKey: 'seriebac' },
            { header: 'Diplomeentree', field: 'diplomeentree', dataKey: 'diplomeentree' },
            { header: 'Moyennebac', field: 'moyennebac', dataKey: 'moyennebac' },
            { header: 'Mentionbac', field: 'mentionbac', dataKey: 'mentionbac' },
            { header: 'Groupepassage', field: 'groupepassage', dataKey: 'groupepassage' },
            { header: 'AnneeBac', field: 'anneeBac', dataKey: 'anneeBac' },
            { header: 'Handicap', field: 'handicap', dataKey: 'handicap' },
            { header: 'TypeHandicap', field: 'typeHandicap', dataKey: 'typeHandicap' },
            { header: 'DescriptionHandicap', field: 'descriptionHandicap', dataKey: 'descriptionHandicap' },
            { header: 'Orphelin', field: 'orphelin', dataKey: 'orphelin' },
            { header: 'SituationMatrimoniale', field: 'situationMatrimoniale', dataKey: 'situationMatrimoniale' },
            { header: 'Nomconjoint', field: 'nomconjoint', dataKey: 'nomconjoint' },
            { header: 'Nbreenfant', field: 'nbreenfant', dataKey: 'nbreenfant' },
            { header: 'Nomcontact', field: 'nomcontact', dataKey: 'nomcontact' },
            { header: 'Telcontact', field: 'telcontact', dataKey: 'telcontact' },
        ];

const allowedEtudiantFieldsForFilter = [
    'cni',
    'ine',
    'numinterne',
    'nometudiant',
    'prenometudiant',
    'genre',
    'datenaiss',
    'lieunaiss',
    'regionnaiss',
    'adville',
    'adquartier',
    'adruevilla',
    'email',
    'emailUniv',
    'notifmail',
    'photo',
    'lyceedeprovenance',
    'teletudiant',
    'teletudiant2',
    'seriebac',
    'diplomeentree',
    'moyennebac',
    'mentionbac',
    'groupepassage',
    'anneeBac',
    'handicap',
    'typeHandicap',
    'descriptionHandicap',
    'orphelin',
    'situationMatrimoniale',
    'nomconjoint',
    'nbreenfant',
    'nomcontact',
    'telcontact',
];

export { etudiantColumns,allowedEtudiantFieldsForFilter };
